const API = location.port === "8787" ? "" : "http://127.0.0.1:8787";
const state = {projects:[], projectId:null, pages:[], pageId:null, entities:{}, formulas:[], prices:[], rab:[], zoom:1, rotation:0, layers:{walls:true,rooms:true,ocr:true,mep:true,routes:true,openings:true}};
const PAGE_CATS=["ARCHITECTURE_PLAN","FOUNDATION_PLAN","STRUCTURAL_PLAN","SECTION_DRAWING","ELECTRICAL_PLAN","PLUMBING_PLAN","ROOF_PLAN","DETAIL_DRAWING","LEGEND_PAGE","SCHEDULE_PAGE","UNKNOWN"];
const MEP=["LAMP_POINT","DOWNLIGHT","WALL_LAMP","SWITCH","SOCKET","AC_POINT","EXHAUST_FAN","PANEL","MCB","GROUNDING_POINT","FLOOR_DRAIN","CLOSET","WASTAFEL","SHOWER","KRAN","CLEAN_OUT","ROOF_DRAIN","SEPTIC_TANK","WATER_TANK","PUMP","PIPE_CLEAN_WATER","PIPE_WASTE_WATER","PIPE_VENT"];
const ROUTES=["CLEAN_WATER_PIPE","WASTE_WATER_PIPE","VENT_PIPE","ELECTRICAL_CONDUIT","MAIN_CABLE_ROUTE","UNKNOWN_ROUTE"];
const qs=(s,r=document)=>r.querySelector(s); const qsa=(s,r=document)=>[...r.querySelectorAll(s)];
const fmt=n=>n==null||n===""?"":Number(n).toLocaleString("id-ID",{maximumFractionDigits:3});
function toast(msg){const el=qs("#toast");el.textContent=msg;el.style.display="block";setTimeout(()=>el.style.display="none",3600)}
async function api(path,opt={}){const res=await fetch(API+path,{headers:{"Content-Type":"application/json",...(opt.headers||{})},...opt});if(!res.ok){let t=await res.text();throw new Error(t||res.statusText)}return res.headers.get("content-type")?.includes("json")?res.json():res.text()}
async function post(path,data={}){return api(path,{method:"POST",body:JSON.stringify({data})})}
async function put(path,data={}){return api(path,{method:"PUT",body:JSON.stringify({data})})}
function switchView(id){qsa(".view").forEach(v=>v.classList.toggle("active",v.id===id));qsa(".nav button").forEach(b=>b.classList.toggle("active",b.dataset.view===id));qs("#viewTitle").textContent=qs(`.nav button[data-view="${id}"]`)?.textContent||"RAB Otomatis";drawOverlay();if(id==="diagnostics")runDiagnostics();if(id==="audit")runAudit();if(id==="rab")loadRab();if(id==="prices")loadPrices();if(id==="formula")loadFormulas();}
function currentPage(){return state.pages.find(p=>p.id===state.pageId)}
async function boot(){fillSelects();bind();await loadProjects();if(!state.projectId)await createDefaultProject();await refreshAll();switchView("dashboard")}
function fillSelects(){qs("#pageCategory").innerHTML=PAGE_CATS.map(x=>`<option>${x}</option>`).join("");qs("#mepClass").innerHTML=MEP.map(x=>`<option>${x}</option>`).join("");qs("#routeType").innerHTML=ROUTES.map(x=>`<option>${x}</option>`).join("")}
function bind(){qsa(".nav button").forEach(b=>b.onclick=()=>switchView(b.dataset.view));qsa("[data-view-link]").forEach(b=>b.onclick=()=>switchView(b.dataset.viewLink));qs("#newProjectBtn").onclick=()=>switchView("projects");qs("#saveProjectBtn").onclick=saveProject;qs("#projectSelect").onchange=async e=>{state.projectId=e.target.value;localStorage.setItem("rab-auto-project",state.projectId);await refreshAll()};qs("#uploadPdfBtn").onclick=uploadPdf;qs("#rasterizeBtn").onclick=rasterize;qs("#saveCategoryBtn").onclick=saveCategory;qs("#saveCalibrationBtn").onclick=saveCalibration;qs("#detectWallsBtn").onclick=detectWalls;qs("#detectRoomsBtn").onclick=detectRooms;qs("#runOcrBtn").onclick=runOcr;qs("#confirmWallsBtn").onclick=()=>bulkConfirm("walls");qs("#confirmRoomsBtn").onclick=()=>bulkConfirm("rooms");qs("#addMepBtn").onclick=addMep;qs("#runYoloBtn").onclick=runYolo;qs("#exportDatasetBtn").onclick=exportDataset;qs("#exportDatasetBtn2").onclick=exportDataset;qs("#addRouteBtn").onclick=addRoute;qs("#addStructBtn").onclick=addStruct;qs("#addFormulaBtn").onclick=addFormula;qs("#addPriceBtn").onclick=addPrice;qs("#importPriceBtn").onclick=importPrice;qs("#generateRabBtn").onclick=generateRab;qs("#refreshRabBtn").onclick=loadRab;qs("#runAuditBtn").onclick=runAudit;qs("#runDiagBtn").onclick=runDiagnostics;qs("#zoomInBtn").onclick=()=>{state.zoom=Math.min(3,state.zoom+.1);renderPage()};qs("#zoomOutBtn").onclick=()=>{state.zoom=Math.max(.2,state.zoom-.1);renderPage()};qs("#rotateBtn").onclick=()=>{state.rotation=(state.rotation+90)%360;renderPage()};qsa("[data-layer]").forEach(c=>c.onchange=e=>{state.layers[e.target.dataset.layer]=e.target.checked;drawOverlay()})}
async function loadProjects(){state.projects=await api("/api/projects");const saved=localStorage.getItem("rab-auto-project");state.projectId=(saved&&state.projects.some(p=>p.id===saved))?saved:state.projects[0]?.id;renderProjects()}
async function createDefaultProject(){const p=await post("/api/projects",{name:"Proyek RAB Baru",type:"Bangunan"});state.projectId=p.id;localStorage.setItem("rab-auto-project",p.id);await loadProjects()}
function renderProjects(){qs("#projectSelect").innerHTML=state.projects.map(p=>`<option value="${p.id}" ${p.id===state.projectId?"selected":""}>${p.name}</option>`).join("");qs("#projectList").innerHTML=state.projects.map(p=>`<div class="list-item"><div><b>${p.name}</b><div class="small">${p.type||""} ${p.location||""}</div></div><button onclick="selectProject('${p.id}')">Buka</button></div>`).join("")}
window.selectProject=async id=>{state.projectId=id;localStorage.setItem("rab-auto-project",id);await refreshAll()}
async function saveProject(){const name=qs("#projectName").value.trim();if(!name)return; if(state.projectId){await put(`/api/projects/${state.projectId}`,{name,type:qs("#projectType").value,location:qs("#projectLocation").value})}else{const p=await post("/api/projects",{name,type:qs("#projectType").value,location:qs("#projectLocation").value});state.projectId=p.id}await loadProjects();toast("Proyek tersimpan")}
async function refreshAll(){if(!state.projectId)return;state.pages=await api(`/api/projects/${state.projectId}/pages`);state.pageId=state.pageId&&state.pages.some(p=>p.id===state.pageId)?state.pageId:state.pages[0]?.id;state.entities=await api(`/api/projects/${state.projectId}/entities`).catch(()=>({}));await Promise.all([loadFormulas(),loadPrices(),loadRab().catch(()=>{})]);renderAll()}
function renderAll(){renderProjects();renderFiles();renderThumbs();renderPage();renderEntities();renderMetrics();updateExportLinks()}
async function renderFiles(){const p=await api(`/api/projects/${state.projectId}`).catch(()=>null);qs("#fileList").innerHTML=(p?.files||[]).map(f=>`<div class="list-item"><div><b>${f.name}</b><div class="small">${f.status} | ${f.pageCount||0} halaman</div></div></div>`).join("")||"<div class='small'>Belum ada PDF.</div>"}
function renderMetrics(){const e=state.entities||{};const rab=state.rab||[];const prices=state.prices||[];const review=rab.filter(x=>["NEEDS_REVIEW","MISSING_DATA"].includes(x.status)).length;const metrics=[["Total Proyek",state.projects.length],["PDF Terupload",state.pages.length?"Ada":"0"],["Halaman Diproses",state.pages.length],["Dinding Terdeteksi",(e.walls||[]).length],["Ruang Terdeteksi",(e.rooms||[]).length],["Simbol MEP",(e.mepSymbols||[]).length],["Item RAB",rab.length],["Item Butuh Review",review],["Harga Perlu Update",prices.filter(p=>p.status==="NEEDS_UPDATE").length]];qs("#metrics").innerHTML=metrics.map(m=>`<div class="metric"><b>${m[1]}</b><span>${m[0]}</span></div>`).join("")}
async function uploadPdf(){const file=qs("#pdfInput").files[0];if(!file)return toast("Pilih PDF dulu");const fd=new FormData();fd.append("file",file);const res=await fetch(API+`/api/projects/${state.projectId}/upload-pdf`,{method:"POST",body:fd});if(!res.ok)throw new Error(await res.text());toast("PDF uploaded");await refreshAll()}
async function rasterize(){const r=await post(`/api/projects/${state.projectId}/rasterize`,{dpi:180});toast(r.status==="OK"?`Rasterize OK: ${r.pages.length} halaman`:r.message);await refreshAll()}
function renderThumbs(){qs("#thumbs").innerHTML=state.pages.map(p=>`<div class="thumb ${p.id===state.pageId?"active":""}" onclick="pickPage('${p.id}')"><img src="${API+p.thumbnailPath}"><div class="small">Hal ${p.pageNumber}<br>${p.category}</div></div>`).join("")||"<div class='small'>Rasterize PDF untuk melihat halaman.</div>"}
window.pickPage=id=>{state.pageId=id;renderThumbs();renderPage()}
function renderPage(){const p=currentPage();const img=qs("#pageImage"),stage=qs("#stage"),ov=qs("#overlay");if(!p){img.removeAttribute("src");ov.innerHTML="";return}img.src=API+p.imagePath;img.onload=()=>{ov.setAttribute("width",img.naturalWidth);ov.setAttribute("height",img.naturalHeight);drawOverlay()};stage.style.transform=`scale(${state.zoom}) rotate(${state.rotation}deg)`;qs("#zoomLabel").textContent=Math.round(state.zoom*100)+"%";qs("#pageCategory").value=p.category||"UNKNOWN";qs("#pageInfo").textContent=`Page ID: ${p.id}\nUkuran: ${p.widthPx} x ${p.heightPx}\nKalibrasi: ${p.calibration&&p.calibration!=="{}"?"Ada":"Belum ada"}`}
async function saveCategory(){if(!state.pageId)return;await put(`/api/pages/${state.pageId}/category`,{category:qs("#pageCategory").value});await refreshAll();toast("Kategori tersimpan")}
function parsePoint(v){const [x,y]=v.split(",").map(Number);return {x:x||0,y:y||0}}
async function saveCalibration(){if(!state.pageId)return;const data={method:qs("#calMethod").value,drawingScaleText:qs("#drawingScale").value,pointA:parsePoint(qs("#pointA").value),pointB:parsePoint(qs("#pointB").value),realDistanceM:Number(qs("#realDistance").value),pixelToMeterRatio:Number(qs("#pixelRatio").value)||undefined,confirmed:true};await put(`/api/pages/${state.pageId}/calibration`,data);await refreshAll();toast("Kalibrasi disimpan")}
async function detectWalls(){if(!state.pageId)return;const r=await post(`/api/pages/${state.pageId}/detect-walls`);toast(`${r.walls.length} kandidat dinding`);await refreshAll()}
async function detectRooms(){if(!state.pageId)return;const r=await post(`/api/pages/${state.pageId}/detect-rooms`);toast(`${r.rooms.length} kandidat ruang`);await refreshAll()}
async function runOcr(){if(!state.pageId)return;const r=await post(`/api/pages/${state.pageId}/run-ocr`);toast(r.message||`${r.results.length} hasil OCR`);await refreshAll()}
async function bulkConfirm(type){const list=type==="walls"?(state.entities.walls||[]):(state.entities.rooms||[]);for(const x of list){await put(`/api/entities/${type}/${x.id}`,{status:"USER_CONFIRMED",confirmed:true,confidence:"HIGH"})}await refreshAll();toast("Data dikonfirmasi")}
function renderEntities(){const e=state.entities||{};table("#wallList",["wallType","lengthM","confidence","status"],e.walls||[],"walls");table("#roomList",["roomName","areaM2","perimeterM","confidence","status"],e.rooms||[],"rooms");table("#ocrList",["text","type","confidence","status"],e.ocrResults||[]);table("#mepList",["className","label","confidence","status"],e.mepSymbols||[],"mep-symbols");table("#routeList",["routeType","lengthM","diameterOrSpec","confidence","status"],e.routes||[],"routes");table("#structList",["itemName","lengthM","widthM","heightM","volumeM3","status"],e.structuralInputs||[],"structural-inputs");qs("#scaleOcrHints").innerHTML=(e.ocrResults||[]).filter(o=>o.type==="SCALE_TEXT"||o.type==="DIMENSION").map(o=>`<div class="list-item"><b>${o.text}</b><span class="tag ${o.confidence}">${o.type}</span></div>`).join("")||"<div class='small'>Jalankan OCR untuk saran skala/dimensi.</div>";drawOverlay()}
function table(sel,cols,rows,entityType){qs(sel).innerHTML=`<table><thead><tr>${cols.map(c=>`<th>${c}</th>`).join("")}<th>Aksi</th></tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(c=>`<td>${renderCell(r[c])}</td>`).join("")}<td>${entityType?`<div class="row-actions"><button onclick="confirmEntity('${entityType}','${r.id}')">Confirm</button><button onclick="delEntity('${entityType}','${r.id}')">Hapus</button></div>`:""}</td></tr>`).join("")}</tbody></table>`}
function renderCell(v){if(v==null)return "";if(typeof v==="number")return fmt(v);if(typeof v==="object")return `<code>${JSON.stringify(v).slice(0,80)}</code>`;return `<span class="tag ${v}">${String(v)}</span>`}
window.confirmEntity=async(t,id)=>{await put(`/api/entities/${t}/${id}`,{status:"USER_CONFIRMED",confirmed:true,confidence:"HIGH"});await refreshAll()}
window.delEntity=async(t,id)=>{await api(`/api/entities/${t}/${id}`,{method:"DELETE"});await refreshAll()}
function boxInput(v){const a=v.split(",").map(Number);return {x:a[0]||0,y:a[1]||0,w:a[2]||28,h:a[3]||28}}
async function addMep(){await post(`/api/pages/${state.pageId}/mep-symbols`,{className:qs("#mepClass").value,boundingBox:boxInput(qs("#mepBox").value),source:"Manual",status:"MANUAL_TAGGED",confidence:"HIGH",confirmed:true});await refreshAll();toast("Tag MEP disimpan")}
async function runYolo(){const r=await post(`/api/pages/${state.pageId}/detect-mep-yolo`);toast(r.message||`${r.detections.length} deteksi YOLO`);await refreshAll()}
async function exportDataset(){const r=await api(`/api/projects/${state.projectId}/export/mep-dataset`);toast(`Dataset MEP dibuat: ${r.symbols} simbol`)}
function parsePolyline(s){return s.split(";").map(p=>parsePoint(p.trim())).filter(p=>p.x||p.y)}
async function addRoute(){await post(`/api/pages/${state.pageId}/routes`,{routeType:qs("#routeType").value,polyline:parsePolyline(qs("#routePolyline").value),diameterOrSpec:qs("#routeSpec").value});await refreshAll();toast("Jalur disimpan")}
async function addStruct(){await post(`/api/pages/${state.pageId}/structural-inputs`,{itemName:qs("#structName").value,category:qs("#structCategory").value,lengthM:Number(qs("#structL").value)||null,widthM:Number(qs("#structW").value)||null,heightM:Number(qs("#structH").value)||null,count:Number(qs("#structCount").value)||1,notes:qs("#structNotes").value,status:"MANUAL_TAGGED"});await refreshAll();toast("Input struktur disimpan")}
async function loadFormulas(){state.formulas=await api("/api/formulas").catch(()=>[]);qs("#formulaList").innerHTML=`<table><thead><tr><th>Nama</th><th>Kategori</th><th>Unit</th><th>Expression</th></tr></thead><tbody>${state.formulas.map(f=>`<tr><td>${f.name}</td><td>${f.category}</td><td>${f.unit}</td><td><code>${f.expression}</code></td></tr>`).join("")}</tbody></table>`}
async function addFormula(){await post("/api/formulas",{name:qs("#formulaName").value,category:qs("#formulaCategory").value,unit:qs("#formulaUnit").value,expression:qs("#formulaExpression").value,variables:[]});await loadFormulas();toast("Formula tersimpan")}
async function loadPrices(){state.prices=await api("/api/prices").catch(()=>[]);qs("#priceList").innerHTML=`<table><thead><tr><th>Item</th><th>Kategori</th><th>Satuan</th><th>Harga</th><th>Status</th></tr></thead><tbody>${state.prices.map(p=>`<tr><td>${p.itemName}</td><td>${p.category}</td><td>${p.unit}</td><td>${fmt(p.approvedPrice)}</td><td><span class="tag ${p.status}">${p.status}</span></td></tr>`).join("")}</tbody></table>`}
async function addPrice(){await post("/api/prices",{itemName:qs("#priceName").value,category:qs("#priceCategory").value,unit:qs("#priceUnit").value,approvedPrice:Number(qs("#priceApproved").value)||0,supplier:qs("#priceSupplier").value,status:"MANUAL"});await loadPrices();renderMetrics();toast("Harga tersimpan")}
async function importPrice(){const file=qs("#priceCsvInput").files[0];if(!file)return;const fd=new FormData();fd.append("file",file);const res=await fetch(API+"/api/prices/import-csv",{method:"POST",body:fd});toast((await res.json()).saved+" harga diimport");await loadPrices()}
async function generateRab(){const r=await post(`/api/projects/${state.projectId}/generate-rab`);toast(`${r.items.length} item RAB dibuat`);await loadRab();switchView("rab")}
async function loadRab(){if(!state.projectId)return;state.rab=await api(`/api/projects/${state.projectId}/rab`).catch(()=>[]);renderRab();renderMetrics()}
function renderRab(){qs("#rabTable").innerHTML=`<table><thead><tr>${["No","Kategori","Uraian Pekerjaan","Satuan","Formula","Parameter","Volume","Harga Satuan","Jumlah Harga","Sumber Data","Confidence","Status","Catatan","Aksi"].map(h=>`<th>${h}</th>`).join("")}</tr></thead><tbody>${state.rab.map((r,i)=>`<tr class="${r.status}"><td>${i+1}</td><td>${r.category}</td><td contenteditable onblur="editRab('${r.id}','itemName',this.textContent)">${r.itemName}</td><td>${r.unit}</td><td>${r.formulaId||""}</td><td><code>${JSON.stringify(r.parameters||{}).slice(0,120)}</code></td><td contenteditable onblur="editRabNum('${r.id}','volume',this.textContent)">${fmt(r.volume)}</td><td contenteditable onblur="editRabNum('${r.id}','unitPrice',this.textContent)">${fmt(r.unitPrice)}</td><td>${fmt(r.totalPrice)}</td><td>${r.source}</td><td><span class="tag ${r.confidence}">${r.confidence}</span></td><td><span class="tag ${r.status}">${r.status}</span></td><td contenteditable onblur="editRab('${r.id}','notes',this.textContent)">${r.notes||""}</td><td><div class="row-actions"><button onclick="confirmRab('${r.id}')">Confirm</button><button onclick="lockRab('${r.id}',${!r.locked})">${r.locked?"Unlock":"Lock"}</button></div></td></tr>`).join("")}</tbody></table>`}
window.editRab=async(id,k,v)=>{await put(`/api/rab/${id}`,{[k]:v});await loadRab()}
window.editRabNum=async(id,k,v)=>{await put(`/api/rab/${id}`,{[k]:Number(String(v).replace(/\D/g,""))||0,manualOverride:k==="volume"});await loadRab()}
window.confirmRab=async id=>{await post(`/api/rab/${id}/confirm`);await loadRab()}
window.lockRab=async(id,locked)=>{await post(`/api/rab/${id}/lock`,{locked});await loadRab()}
async function runAudit(){if(!state.projectId)return;const r=await api(`/api/projects/${state.projectId}/audit`);const html=`<table><thead><tr><th>Issue</th><th>Severity</th><th>Related Item</th><th>Source</th><th>Recommended Action</th><th>Status</th></tr></thead><tbody>${r.issues.map(i=>`<tr><td>${i.issue}</td><td><span class="tag ${i.severity}">${i.severity}</span></td><td>${i.relatedItem}</td><td>${i.source}</td><td>${i.recommendedAction}</td><td>${i.status}</td></tr>`).join("")}</tbody></table>`;qs("#auditList").innerHTML=html;qs("#dashboardAudit").innerHTML=r.issues.slice(0,5).map(i=>`<div class="issue ${i.severity}"><b>${i.severity}</b> ${i.issue}<div class="small">${i.recommendedAction}</div></div>`).join("")||"<div class='small'>Tidak ada issue audit utama.</div>"}
async function runDiagnostics(){const d=await api("/api/diagnostics");qs("#diagList").innerHTML=`<table><thead><tr><th>Check</th><th>Status</th><th>Info</th></tr></thead><tbody>${Object.entries(d).map(([k,v])=>`<tr><td>${k}</td><td><span class="tag ${v.status}">${v.status}</span></td><td>${v.message}</td></tr>`).join("")}</tbody></table>`}
function updateExportLinks(){if(!state.projectId)return;qs("#exportRabCsv").href=API+`/api/projects/${state.projectId}/export/rab-csv`;qs("#exportRabJson").href=API+`/api/projects/${state.projectId}/export/rab-json`;qs("#exportPrintable").href=API+`/api/projects/${state.projectId}/export/printable-html`;qs("#exportAudit").href=API+`/api/projects/${state.projectId}/export/audit`}
function drawOverlay(){const p=currentPage(),ov=qs("#overlay");if(!p||!ov)return;const e=state.entities||{};ov.innerHTML="";if(state.layers.walls)(e.walls||[]).filter(x=>x.pageId===p.id).forEach(w=>line(w.polyline,"overlay-wall",w.id));if(state.layers.rooms)(e.rooms||[]).filter(x=>x.pageId===p.id).forEach(r=>poly(r.polygon,"overlay-room",r.id));if(state.layers.ocr)(e.ocrResults||[]).filter(x=>x.pageId===p.id).forEach(o=>rect(o.boundingBox,"overlay-ocr",o.text));if(state.layers.mep)(e.mepSymbols||[]).filter(x=>x.pageId===p.id).forEach(m=>rect(m.boundingBox,"overlay-mep",m.className));if(state.layers.routes)(e.routes||[]).filter(x=>x.pageId===p.id).forEach(r=>line(r.polyline,"overlay-route",r.routeType));if(state.layers.openings)(e.openings||[]).filter(x=>x.pageId===p.id).forEach(o=>rect(o.boundingBox,"overlay-opening",o.type))}
function line(points,cls,title){if(!points?.length)return;const el=document.createElementNS("http://www.w3.org/2000/svg","polyline");el.setAttribute("points",points.map(p=>`${p.x},${p.y}`).join(" "));el.setAttribute("class",cls);el.innerHTML=`<title>${title}</title>`;qs("#overlay").append(el)}
function poly(points,cls,title){if(!points?.length)return;const el=document.createElementNS("http://www.w3.org/2000/svg","polygon");el.setAttribute("points",points.map(p=>`${p.x},${p.y}`).join(" "));el.setAttribute("class",cls);el.innerHTML=`<title>${title}</title>`;qs("#overlay").append(el)}
function rect(b,cls,title){if(!b)return;const el=document.createElementNS("http://www.w3.org/2000/svg","rect");el.setAttribute("x",b.x||0);el.setAttribute("y",b.y||0);el.setAttribute("width",b.w||20);el.setAttribute("height",b.h||20);el.setAttribute("class",cls);el.innerHTML=`<title>${title}</title>`;qs("#overlay").append(el)}
window.addEventListener("error",e=>toast(e.message));boot().catch(e=>toast(e.message));
